name: Check Compliance
run-name: Checking code compliance
on:
  pull_request_target:
    types:
      - opened
jobs:
  check-for-compliance:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@main
      - name: "Check Pep8 Compliance"
        run: |
          sudo apt-get install -y pycodestyle
          pycodestyle --ignore E123,E124,E126,E127,E202,E221,E222,E241 .
      - name: "Check Mypy Compliance"
        run: |
          sudo apt-get install -y mypy
          mypy --disallow-any-generics .